server:
  port: 8081

spring:
  application:
    name: auth-user-service

  data:
    mongodb:
      uri: mongodb+srv://educonnect:educonnect123@educonnect.sjmtr4c.mongodb.net/educonnect
      database: educonnect
      auto-index-creation: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: my-super-secret-jwt-key-for-educonnect-platform-minimum-256-bits-required
  expiration: 86400000
  refresh-expiration: 604800000

services:
  notification:
    url: http://localhost:8085
  learning:
    url: http://localhost:8084

app:
  password-reset:
    token-expiration: 3600000
  two-factor:
    enabled: true
  frontend:
    url: http://localhost:5173

logging:
  level:
    root: INFO